test_case: True
full_matrix: False

guest_name: 'vm1'
new_vcpu: 10
maxmem: 1024
target_mem: 512
src_host: 'source host'
cpu_plug: 'up'
guest_xml: 'guest.xml'
pagesize: '2048'
hugetlbfs_mount: '/dev/hugetest'
memtune:
    hardlimit: 100
restart_libvirtd: True
curmem: 1048576
memballoon:
    model: 'none'
mem_period: 2
